export { AntiDetectBrowser } from './browser'
export {
  listProfiles,
  profileExists,
  getProfileDir,
  listProfileEntries,
  getProfilesDir,
  TEMPORARY_PROFILES_DIR,
  type ProfileRootOptions,
} from './profile'
export {
  clearTemporaryProfiles,
  temporaryProfileLastUsed,
  type ClearTemporaryOptions,
  type ClearedTemporaryProfile,
} from './temporary-profiles'
export {
  createProfile,
  updateProfile,
  getProfile,
  getOrCreateProfile,
  listServerProfiles,
  deleteProfile,
  syncPullProfiles,
  getProfileForLaunch,
  getProfileArchiveUrls,
  getProfileArchiveUploadUrl,
  listProxies,
  claimManagedProxy,
  releaseManagedProxy,
  swapManagedProxy,
  activateProxy,
  managedProxyToRelayUrl,
  DEFAULT_RELAY_HOST,
  issueProxyTicket,
  revokeProxyTicket,
  getAccount,
  createUserProxy,
  updateUserProxy,
  deleteUserProxy,
  syncPullUserProxies,
  proxyConfigToUrl,
  type ManagedProxy,
  type ProxyQuota,
  type ProxyTicket,
  type AccountInfo,
  type UpdateProfileOptions,
  type LaunchProfile,
} from './api'

export { LiveViewStream, registerLiveSession, unregisterLiveSession } from './liveview'
export { uploadProfileState, downloadProfileState } from './api'
export { lookupProxyGeo, lookupCurrentGeo, type GeoInfo } from './geo'
export { checkClientVersion, SDK_VERSION, type VersionCheckResult } from './version'
export {
  openProfile,
  ensureKernel,
  KERNEL_VERSIONS,
  DEFAULT_KERNEL_VERSION,
  defaultKernelVersion,
  isKernelInstalled,
  findKernelVersion,
  findKernelVersionStrict,
  normalizeKernelVersion,
  migrateLegacyKernelDirs,
  listInstalledKernels,
  kernelDirSize,
  deleteKernel,
  kernelDir,
  kernelAvailableOnPlatform,
  kernelsForPlatform,
  allKernelVersions,
  registerKernelVersions,
  fetchRemoteKernelVersions,
  refreshKernelVersions,
  loadCachedKernelVersions,
  KERNEL_MANIFEST_URL,
  KERNEL_MANIFEST_TTL_MS,
  KERNEL_VERSION_CACHE_FILE,
  currentPlatform,
  installedKernelBuild,
  writeInstalledKernelBuild,
  kernelUpdateStatus,
  installedKernelUpdates,
  kernelSupportsAndroid,
  kernelReadsAppLocaleFromConfig,
  androidCapableKernels,
  resolveAndroidKernel,
  ANDROID_MIN_KERNEL_VERSION,
  defaultCacheDir,
  lookupEngineProxyGeo,
  probeProxyExit,
  generatePersona,
  loadOrGeneratePersona,
  readPersona,
  writePersona,
  withKernelVersion,
  setProfileKernelVersion,
  fetchRealDevice,
  packProfileCache,
  packProfileCacheWithReport,
  lastProfilePackReport,
  type ProfilePackReport,
  type ProfilePackResult,
  unpackProfileCache,
  exportProfileArchive,
  exportProfileArchiveAsync,
  type ExportProfileArchiveOptions,
  importProfileArchive,
  PROFILE_ARCHIVE_EXT,
  downloadProfileCache,
  uploadProfileCache,
  ARCHIVE_VERSION_FILE,
  readArchiveVersion,
  writeArchiveVersion,
  clearArchiveVersion,
  normalizeArchiveVersion,
  readProfileMeta,
  writeProfileMeta,
  isProfileEncrypted,
  markProfileEncrypted,
  unmarkProfileEncrypted,
  readCryptState,
  writeCryptState,
  settleCryptState,
  profileCryptMarker,
  isCryptKeyPending,
  markCryptKeyPending,
  clearCryptKeyPending,
  type CryptSettlement,
  CRYPT_STATE_FILE,
  CRYPT_PENDING_FILE,
  fetchProfileCryptKey,
  parseCryptKeyBody,
  resolveCryptKey,
  resolveProfileDir,
  resolveProfileDirSync,
  type ProfileMeta,
  type ProfileEntry,
  type EngineSession,
  type OpenedProfile,
  type ArchiveSyncEvent,
  type ProxyGeo,
  type ProxyProbeResult,
  type KernelVersion,
  type KernelUpdateStatus,
  type Persona,
  type ApiLogMode,
  type DeviceType,
  type CapturedFacts,
  type PersonaInit,
  type RealDevice,
  type PortableProfileMeta,
  type ImportedProfileMeta,
  type SetProfileKernelVersionOptions,
} from './engine'

export { managedProxyDisplayName, managedProxyShortId } from './proxy-display'
export { profile, ProfileHandle, type ProfileOptions, type SessionOptions } from './profile-handle'
export type { ProxyInput, ProxyBinding } from './proxy-binding'
export type {
  AntiDetectBrowserOptions,
  LaunchOptions,
  LaunchResult,
  McpSession,
  LiveViewStreamOptions,
  SyncedProxyRef,
  ProfileConfig,
  SyncedProfile,
  ProfileSyncPage,
  ProxyConfig,
  SyncedProxy,
  ProxySyncPage,
} from './types'
