"""Regenerate src/antibrow/android_devices.py from the device corpus.

The free tier ships three Android devices in-package so an Android profile can
be created offline. Picked for spread: two GPU families, three screen sizes.

Run: python scripts/gen_android_devices.py <path-to>/real-devices.json
"""
import json
import pprint
import sys
from pathlib import Path

MODELS = ["SM-S918U", "moto g05", "SM-S936U"]

if len(sys.argv) < 2:
    sys.exit("usage: python scripts/gen_android_devices.py <real-devices.json>")

corpus = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
picked = []
for model in MODELS:
    row = next((d for d in corpus["devices"] if d["os"] == "android" and d.get("model") == model), None)
    if row is None:
        sys.exit("corpus is missing {0}".format(model))
    picked.append({k: v for k, v in row.items() if k != "weight"})

header = '''"""Generated by scripts/gen_android_devices.py - do not edit by hand.

Three real Android devices shipped in-package so the free tier can create an
Android profile with no network round-trip. Each entry is one machine's bound
set of facts: the screen, the GPU report and the UA client hints only agree
with each other because they came off the same device, so pick a whole row,
never a field.
"""

from typing import Any, Dict, List

ANDROID_FALLBACK_DEVICES: List[Dict[str, Any]] = '''

dest = Path(__file__).resolve().parent.parent / "src" / "antibrow" / "android_devices.py"
dest.write_text(header + pprint.pformat(picked, indent=4, width=100, sort_dicts=True) + "\n", encoding="utf-8")
print("wrote {0}".format(dest))
