"""Regenerate src/antibrow/android_devices.py from the device corpus.

The free tier ships three Android devices in-package so an Android profile can
be created offline. Picked for spread: two GPU families, three screen sizes.

Run: python scripts/gen_android_devices.py <path-to>/real-devices.json
"""
import json
import pprint
import sys
from pathlib import Path

# Pinned by model *and* screen: several captures of the same phone differ only
# by the browser's display-size setting, and picking whichever the corpus lists
# first would silently swap the machine every free-tier profile is built on.
MODELS = [
    ("SM-S918U", 384, 824),
    ("moto g05", 412, 917),
    ("SM-S936U", 320, 694),
]

if len(sys.argv) < 2:
    sys.exit("usage: python scripts/gen_android_devices.py <real-devices.json>")

corpus = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
picked = []
for model, width, height in MODELS:
    rows = [
        d
        for d in corpus["devices"]
        if d["os"] == "android"
        and d.get("model") == model
        and d["screen"]["width"] == width
        and d["screen"]["height"] == height
    ]
    # A row whose capture resolved no WebGPU adapter would leave the profile's
    # navigator.gpu answering for the host machine.
    row = next((d for d in rows if d.get("webgpu")), rows[0] if rows else None)
    if row is None:
        sys.exit("corpus is missing {0} {1}x{2}".format(model, width, height))
    picked.append({k: v for k, v in row.items() if k != "weight"})

header = '''"""Generated by scripts/gen_android_devices.py - do not edit by hand.

Three real Android devices shipped in-package so the free tier can create an
Android profile with no network round-trip. Each entry is one machine's bound
set of facts: the screen, the GPU report and the UA client hints only agree
with each other because they came off the same device, so pick a whole row,
never a field.
"""

from typing import Any, Dict, List

ANDROID_FALLBACK_DEVICES: List[Dict[str, Any]] = '''

dest = Path(__file__).resolve().parent.parent / "src" / "antibrow" / "android_devices.py"
dest.write_text(header + pprint.pformat(picked, indent=4, width=100, sort_dicts=True) + "\n", encoding="utf-8")
print("wrote {0}".format(dest))
