"""AntiBrow - the antidetect browser your AI agent can drive.

Kernel-level fingerprint spoofing, unlimited local profiles, and the plain
Playwright API you already write::

    from antibrow import launch

    browser = launch()
    page = browser.new_page()
    page.goto("https://example.com")
    browser.close()

Fingerprints are spoofed inside a custom Chromium build (C++/Blink), not with
JavaScript patches that anti-bot vendors flag on sight, and every signal -
Canvas, WebGL, WebGPU, fonts, audio, ``navigator``, screen, timezone - comes
from one coherent persona that is frozen per profile.

See https://antibrow.com and the project README for the full API.
"""

from __future__ import annotations

__version__ = "0.14.1"

from .api import (
    DEFAULT_RELAY_HOST,
    AccountInfo,
    LaunchProfile,
    ManagedProxy,
    ProfileConfig,
    ProfileState,
    ProfileStateCookie,
    ProfileStateOrigin,
    ProfileSyncPage,
    ProxyActivation,
    ProxyConfig,
    ProxyListing,
    ProxyQuota,
    ProxyRef,
    ProxySyncPage,
    ProxyTicket,
    SyncedProfile,
    SyncedProxy,
    activate_proxy,
    claim_managed_proxy,
    create_profile,
    create_user_proxy,
    delete_profile,
    delete_user_proxy,
    download_profile_state,
    get_account,
    get_or_create_profile,
    get_profile,
    get_profile_for_launch,
    issue_proxy_ticket,
    list_proxies,
    list_server_profiles,
    list_user_proxies,
    managed_proxy_to_relay_url,
    proxy_config_to_url,
    release_managed_proxy,
    revoke_proxy_ticket,
    swap_managed_proxy,
    sync_pull_profiles,
    sync_pull_user_proxies,
    update_profile,
    update_user_proxy,
    upload_profile_state,
)
from .browser import (
    Antibrow,
    ArchivePlan,
    AsyncAntibrow,
    LaunchPlan,
    ProxyTicketRef,
    SyncEvent,
    launch,
    launch_async,
    launch_persistent_context,
    launch_persistent_context_async,
    prepare_launch,
    set_profile_kernel_version,
)
from .config import (
    TEMPORARY_PROFILES_DIR_NAME,
    config_dir,
    default_cache_dir,
    default_server,
    list_profiles,
    profile_dir,
    profile_exists,
    profiles_dir,
)
from .crypt_key import (
    fetch_profile_crypt_key,
    parse_crypt_key_body,
    resolve_crypt_key,
)
from .crypt_rekey import (
    NO_CRYPT_KEY,
    REKEY_TIMEOUT_CODE,
    build_rekey_args,
    parse_rekey_code,
    run_crypt_rekey,
)
from .devices import fetch_real_device
from .errors import (
    AntibrowError,
    ApiError,
    ConcurrencyLimitError,
    CryptKeyError,
    CryptRekeyError,
    KernelDownloadError,
    LaunchError,
    LicenseError,
    LiveViewError,
    ProfileCacheError,
    ProxyError,
    UnsupportedPlatformError,
)
from .geoip import ProxyGeo, lookup_proxy_geo
from .kernel import (
    ANDROID_MIN_KERNEL_VERSION,
    KERNEL_MANIFEST_URL,
    KERNEL_VERSIONS,
    KernelUpdateStatus,
    KernelVersion,
    android_capable_kernels,
    current_platform,
    default_kernel_version,
    delete_kernel,
    ensure_kernel,
    find_kernel_version,
    find_kernel_version_strict,
    installed_kernel_updates,
    is_kernel_installed,
    kernel_dir,
    kernel_dir_size,
    kernel_supports_android,
    kernel_version_at_least,
    kernels_for_platform,
    list_installed_kernels,
    load_cached_kernel_versions,
    migrate_legacy_kernel_dirs,
    normalize_kernel_version,
    refresh_kernel_catalogue,
    refresh_kernel_versions,
    resolve_android_kernel,
)
from .license import LicenseInfo, fetch_license_token, get_license_token
from .liveview import (
    DEFAULT_RELAY_URL,
    LiveViewOptions,
    LiveViewRegistration,
    LiveViewSession,
    LiveViewStream,
    heartbeat_live_session,
    register_live_session,
    unregister_live_session,
)
from .persona import (
    DeviceType,
    Persona,
    generate_persona,
    load_or_generate_persona,
    persona_to_fp_config,
    read_persona,
    with_kernel_version,
    write_persona,
)
from .portable import (
    PROFILE_ARCHIVE_EXT,
    ImportedProfileMeta,
    PortableProfileMeta,
    copy_portable_profile_files,
    export_profile_archive,
    import_profile_archive,
)
from .profile_cache import (
    ProfilePackResult,
    download_profile_cache,
    last_profile_pack_report,
    pack_profile_cache,
    pack_profile_cache_with_report,
    unpack_profile_cache,
    upload_profile_cache,
)
from .profile_dir import (
    CRYPT_PENDING_FILE,
    CRYPT_STATE_FILE,
    ProfileEntry,
    ProfileMeta,
    clear_crypt_key_pending,
    is_crypt_key_pending,
    is_profile_encrypted,
    list_profile_entries,
    mark_crypt_key_pending,
    mark_profile_encrypted,
    profile_crypt_marker,
    read_crypt_state,
    read_profile_meta,
    resolve_profile_dir,
    settle_crypt_state,
    unmark_profile_encrypted,
    write_crypt_state,
    write_profile_meta,
)
from .profile_sync import (
    ArchiveUrls,
    ensure_server_profile,
    get_profile_archive_upload_url,
    get_profile_archive_urls,
)
from .proxy import ProxySpec, parse_proxy
from .temporary_profiles import (
    ClearedTemporaryProfile,
    clear_temporary_profiles,
    temporary_profile_last_used,
)

__all__ = [
    "__version__",
    # launching
    "launch",
    "launch_async",
    "launch_persistent_context",
    "launch_persistent_context_async",
    "prepare_launch",
    "Antibrow",
    "AsyncAntibrow",
    "LaunchPlan",
    "ArchivePlan",
    "SyncEvent",
    # kernels
    "KERNEL_VERSIONS",
    "KERNEL_MANIFEST_URL",
    "KernelVersion",
    "KernelUpdateStatus",
    "current_platform",
    "default_kernel_version",
    "find_kernel_version",
    "find_kernel_version_strict",
    "kernels_for_platform",
    "ensure_kernel",
    "is_kernel_installed",
    "list_installed_kernels",
    "installed_kernel_updates",
    "refresh_kernel_catalogue",
    "refresh_kernel_versions",
    "load_cached_kernel_versions",
    "kernel_dir",
    "kernel_dir_size",
    "delete_kernel",
    "normalize_kernel_version",
    "migrate_legacy_kernel_dirs",
    # android device profiles
    "DeviceType",
    "fetch_real_device",
    "kernel_supports_android",
    "android_capable_kernels",
    "resolve_android_kernel",
    "kernel_version_at_least",
    "ANDROID_MIN_KERNEL_VERSION",
    # profiles and identity
    "Persona",
    "generate_persona",
    "load_or_generate_persona",
    "read_persona",
    "write_persona",
    "with_kernel_version",
    "set_profile_kernel_version",
    "persona_to_fp_config",
    "list_profiles",
    "profile_exists",
    "profile_dir",
    "profiles_dir",
    "resolve_profile_dir",
    "list_profile_entries",
    "read_profile_meta",
    "write_profile_meta",
    "ProfileMeta",
    "ProfileEntry",
    "default_cache_dir",
    "config_dir",
    "default_server",
    "TEMPORARY_PROFILES_DIR_NAME",
    "ClearedTemporaryProfile",
    "clear_temporary_profiles",
    "temporary_profile_last_used",
    # cloud sync and portable archives
    "ArchiveUrls",
    "get_profile_archive_upload_url",
    "get_profile_archive_urls",
    "ensure_server_profile",
    "pack_profile_cache",
    "pack_profile_cache_with_report",
    "last_profile_pack_report",
    "ProfilePackResult",
    "unpack_profile_cache",
    "download_profile_cache",
    "upload_profile_cache",
    "PROFILE_ARCHIVE_EXT",
    "PortableProfileMeta",
    "ImportedProfileMeta",
    "export_profile_archive",
    "import_profile_archive",
    "copy_portable_profile_files",
    # profile encryption
    "CRYPT_STATE_FILE",
    "CRYPT_PENDING_FILE",
    "is_profile_encrypted",
    "mark_profile_encrypted",
    "unmark_profile_encrypted",
    "read_crypt_state",
    "write_crypt_state",
    "is_crypt_key_pending",
    "mark_crypt_key_pending",
    "clear_crypt_key_pending",
    "profile_crypt_marker",
    "settle_crypt_state",
    "fetch_profile_crypt_key",
    "parse_crypt_key_body",
    "resolve_crypt_key",
    "NO_CRYPT_KEY",
    "REKEY_TIMEOUT_CODE",
    "build_rekey_args",
    "parse_rekey_code",
    "run_crypt_rekey",
    # cloud profiles
    "SyncedProfile",
    "ProfileConfig",
    "ProfileSyncPage",
    "ProxyRef",
    "LaunchProfile",
    "create_profile",
    "get_profile",
    "get_or_create_profile",
    "update_profile",
    "delete_profile",
    "list_server_profiles",
    "sync_pull_profiles",
    "get_profile_for_launch",
    # portable cookie / storage state
    "ProfileState",
    "ProfileStateCookie",
    "ProfileStateOrigin",
    "upload_profile_state",
    "download_profile_state",
    # managed proxies
    "DEFAULT_RELAY_HOST",
    "ManagedProxy",
    "ProxyQuota",
    "ProxyListing",
    "ProxyActivation",
    "ProxyTicket",
    "ProxyTicketRef",
    "list_proxies",
    "claim_managed_proxy",
    "release_managed_proxy",
    "swap_managed_proxy",
    "activate_proxy",
    "issue_proxy_ticket",
    "revoke_proxy_ticket",
    "managed_proxy_to_relay_url",
    # your own proxies
    "ProxyConfig",
    "SyncedProxy",
    "ProxySyncPage",
    "create_user_proxy",
    "update_user_proxy",
    "delete_user_proxy",
    "list_user_proxies",
    "sync_pull_user_proxies",
    "proxy_config_to_url",
    # account
    "AccountInfo",
    "get_account",
    # live view
    "DEFAULT_RELAY_URL",
    "LiveViewOptions",
    "LiveViewRegistration",
    "LiveViewSession",
    "LiveViewStream",
    "register_live_session",
    "unregister_live_session",
    "heartbeat_live_session",
    # proxies and geo
    "ProxySpec",
    "parse_proxy",
    "ProxyGeo",
    "lookup_proxy_geo",
    # licensing
    "LicenseInfo",
    "get_license_token",
    "fetch_license_token",
    # errors
    "AntibrowError",
    "ApiError",
    "LiveViewError",
    "LaunchError",
    "LicenseError",
    "ConcurrencyLimitError",
    "CryptKeyError",
    "CryptRekeyError",
    "KernelDownloadError",
    "ProfileCacheError",
    "ProxyError",
    "UnsupportedPlatformError",
]
